# Generated by cucumber-sinatra. (2015-01-13 09:51:47 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bookmarkmanager.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = bookmarkmanager

class bookmarkmanagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  bookmarkmanagerWorld.new
end
